apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: crossplane-playground
servers: 1
agents: 2
image: rancher/k3s:v1.26.9-k3s1
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
