# https://marketplace.upbound.io/providers/upbound/provider-family-aws/v0.42.0/resources/aws.upbound.io/ProviderConfig/v1beta1
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  endpoint:
    services: [iam, s3]
    url:
      type: Static
      static: http://localstack.default.svc.cluster.local:4566
    hostnameImmutable: true
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: creds
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_requesting_account_id: true
  s3_use_path_style: true
