apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket
spec:
  resources:
    - name: s3Bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        metadata:
          name: bucket-placeholder
        spec:
          forProvider:
            region: us-east-1
          providerConfigRef:
            name: default
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "metadata.name"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.location"
          toFieldPath: "spec.forProvider.region"
  compositeTypeRef:
    apiVersion: crossplane.example.com/v1alpha1
    kind: Blob
